### ISSUE TITLE
[Android Bootcamp] Pre-work - Review my app

### ISSUE THREAD

**Issue by yasuosm** [yasuosm/coderschool-simple-todo#1]
My app is complete, please review. /cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Android submission, yasuosm!

 :innocent: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by yasuosm** [comment]
Thank you, coderschoolreview!

**Comment by hoanle** [comment]
hi @yasuosm 
Thanks for the submission

In general
- App runs without critical issue (crashes, database issue)
- Code is neat
- Good practice of storing string, value in resource file

Detail & suggestion
- You forgot to check empty item. So now i can create several empty items by clicking on ADD ITEM button
- You should try using DialogFragment 
- There are several ways to boost performance of ListView, using ViewHolder for example. Try to write a custom Adapter, use ViewHolder

**Comment by yasuosm** [comment]
Hi @hoanle
Thank for your suggestions. I will update my app in remaining time.

**Comment by yasuosm** [comment]
Hi @coderschoolreview @hoanle 

My app is updated, please review.
New features:
- Persist the todo items into SQLite instead of a text file
- Improve style of the todo items in the list using a custom adapter
- Add support for completion due dates for todo items (and display within listview item)
- Use a DialogFragment instead of new Activity for editing items
- Check empty input
- Use CoordinatorLayout and FloatingActionButton for Add new item
- Ordering todo list by Due date
